### ISSUE TITLE
[Suggestion] Add CMake Support for Cross Platform Building

### ISSUE THREAD

**Issue by ptsouchlos** [masesk/easy-socket#2]
Since this library is intended to work on Windows/Linux, it might be prudent to add CMake support for the library so I can be built natively on Linux by users if they so choose. If this is desired I can file a PR.

Thanks!

**Comment by masesk** [comment]
Awesome suggestion! I have gone ahead and added cmake scripts in v0.2. #
Feel free to let me know if I missed anything.
Best Regards. #11

**Comment by ptsouchlos** [comment]
I'll take a look and let you know, thanks for the follow up.

**Comment by ptsouchlos** [comment]
I've made some changes and filed a PR (#12), let me know what you think.
